### ISSUE TITLE
serctl:readx receives any message sent to the calling process

### ISSUE THREAD

**Issue by JayThomason** [msantos/srly#1]
While using srly I noticed that serctl:readx/3 receives any message sent to the calling process. It seems like this behavior should be documented -- this was a point of confusion for me until I looked at the source code. 

I notice that the readme has improving documentation as a todo item. Should I open a PR or do you want to fix this?

**Comment by msantos** [comment]
Hi Jay! That is actually a really, really dumb bug. The data should have been tagged for a selective receive. Thanks for catching this! I will push a fix in a bit.

**Comment by msantos** [comment]
Should be fixed. If you run into any more problems or have any questions, be sure to let me know!
