### ISSUE TITLE
Running on rebar3 doesn't work

### ISSUE THREAD

**Issue by jj1bdx** [msantos/srly#4]
`make` says:

```
make: *** No rule to make target 'rebar3', needed by 'compile'.  Stop.
```

Also, even if manually compiling with rebar3 as `rebar3 compile`, only NIFs under `c_src` are compiled; using old rebar works without problem.

**Comment by msantos** [comment]
Thanks, should be fixed!

rebar3 puts the beam files in the _build directory (_build/default/lib/srly/ebin/). If it's not working, let me know!

**Comment by jj1bdx** [comment]
@msantos Thx for info. I'll check out rebar3 details by myself. You've saved my day working on Arduino UNO R3. Thx again.

**Comment by waisbrot** [comment]
I was able to build with rebar3 without any problems
