### ISSUE TITLE
What does this answer mean?

### ISSUE THREAD

**Issue by heiheshang** [msantos/srly#5]
2> serctl:open("/dev/ttyACM0").
{ok,<<>>}

**Comment by msantos** [comment]
On Sat, Apr 15, 2017 at 10:42:58PM -0700, heiheshang wrote:
> 2> serctl:open("/dev/ttyACM0").
> {ok,<<>>}

The empty binary is a resource aka magic binary. It's basically a
pointer to some internal state allocated by srly.

See the "Resource objects" section in the erl_nif documentation:

http://erlang.org/doc/man/erl_nif.html

**Comment by heiheshang** [comment]
Why empty? I know what com port is available

**Comment by msantos** [comment]
You're serial port was successfully opened. If you use the returned value, it should work:
~~~
{ok, FD} = serctl:open("/dev/ttyACM0"),
serctl:read(FD, 1024).
~~~
The fact that the resource looks like an empty binary is an implementation detail of native functions. It is not an empty binary but a reference to internal state. See the URL above for details.
